#!/bin/bash
# Este script displaya la fecha, hora, nombre de 
# usuario y directorio actual

        echo "Fecha y hora:"
        date
        echo
        echo "Tu usuario es: `whoami` "
        echo -n "Tu directorio actual es: "
        pwd

