#!/bin/bash

# Este script utilza select para tratar una serie de opciones

OPCIONES="Hola Salir"
select opt in $OPCIONES; do
    if [ "$opt" = "Salir" ]; then
        echo done
        exit
    elif [ "$opt" = "Hola" ]; then
        echo Hola Mundo
    else
        clear
        echo opción errónea
    fi
done
