#!/bin/bash
# Bash Menu Script Example

# Otro ejemplo donde vemos que podemos añadir break a las opciones que queramos que 
# finalicen el bucle

# Ademas las opciones las crea como un array con [@] vuelca todos los valore del array

PS3='Please enter your choice: '
options=("Option 1" "Option 2" "Option 3" "Quit")
echo ${options[@]}
select opt in "${options[@]}"
do
    case $opt in
        "Option 1")
            echo "you chose choice 1"
            ;;
        "Option 2")
            echo "you chose choice 2"
            ;;
        "Option 3")
            echo "you chose choice 3"
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done


