#!/bin/bash
#
#Este script realiza un bucle con for al estilo C 
#

# for i in `seq $1 $2`; do
#     echo $i
# done   


if [ $1 -gt $2 ]; then
    for i in `seq $1 -1 $2`; do
        echo $i
    done   
else
    for i in `seq $1 $2`; do
        echo $i
    done   
fi

