#!/bin/bash

function linea(){
echo
echo "---------------------------------------"
echo
};

function fin(){
linea
exit $1
};

# Basic arithmetic using let
let a=5+4
echo a=$a # 9

let "a = 5 + 4"  #usamos espacios
echo a=$a # 9

let a++
echo a=$a # 10

let "a = 4 * 5"
echo a=$a # 20

echo "Primer parametro es [$1]"
let "a = $1 + 30"
echo a=$a # 30 + first command line argument

let a--
echo a=$a # 30 + first command line argument - 1

linea

valor=$a
modulo=5
let resto=$valor%$modulo
let "dividido = $valor / 5"
echo "$valor / 5 es $dividido"
echo "$valor % $modulo es $resto"

let "ampliado=$resto * 5"
echo "resto=$resto * 5 = $ampliado"

linea


# Basic arithmetic using expr
expr 5 + 4
expr "5 + 4"
expr 5+4
expr 5 \* $1
expr $1 / 5
expr 11 % 2
a=$( expr $1 - 3 )
echo $a

linea

# Basic arithmetic using double parentheses
a=$(( 4 + 5 ))
echo a=$a # 9
a=$((3+5))
echo a=$a # 8
b=$(( a + 3 ))  #No necesitamos $
echo b=$b # 11
b=$(( $a + 4 ))
echo b=$b # 12
(( b++ ))
echo b=$b # 13
(( b += 3 ))
echo b=$b # 16
a=$(( 4 * 5 ))
echo a=$a # 20
a=$(($a / 5))

echo a=$a  # 4

echo $(( a * 3 ))

linea 
